# replace "catw-next-2023" in the three targets below with your actual project(s)
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: sds-demo-pipeline
description: sds demo application delivery pipeline
serialPipeline:
 stages:
 - targetId: prod
   profiles:
   - prod
   strategy:
    canary:
      runtimeConfig:
        kubernetes:
          serviceNetworking:
            service: "sds-demo"
            deployment: "sds-demo"
      canaryDeployment:
        percentages: [5]
        verify: true
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: prod cluster 1
gke:
  cluster: projects/damith-sds/locations/us-central1/clusters/prodcluster1