apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: sds-demo
build:
  artifacts:
  - image: sds-demo
    context: app
    docker:
      dockerfile: Dockerfile
manifests:
  kustomize:
    paths: 
      - k8s/overlays/dev
verify:
- name: successful-request
  executionMode:
    kubernetesCluster: {}
  container:
    name: verification
    image: alpine
    command: ["sh"]
    args:
    - -c
    - |
      set -ex
      REQUEST_COUNT=100
      for _ in $(seq $REQUEST_COUNT)
      do
        wget http://sds-demo:8080 -O /dev/null
      done
portForward:
- resourceType: deployment
  resourceName: sds-demo
  port: 8080 
  localPort: 8080
profiles:
  - name: staging
    manifests:
      kustomize:
        paths: 
          - k8s/overlays/staging
  - name: prod
    manifests:
      kustomize:
        paths: 
          - k8s/overlays/prod