apiVersion: apps/v1
kind: Deployment
metadata:
  name: sds-demo
  labels:
    app: sds-demo
spec:
  selector:
    matchLabels:
      app: sds-demo
  replicas: 1
  minReadySeconds: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: sds-demo
    spec:
      containers:
      - image: sds-demo
        name: sds-demo
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "50m"
        readinessProbe:
          periodSeconds: 1
          httpGet:
            path: /h
            port: 8080
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
          - name: DEV_EXT_IP
            value: "8.8.8.8"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name