apiVersion: apps/v1
kind: Deployment
metadata:
  name: sds-demo
  labels:
    env: test
spec:
  template:
    spec:
      containers:
      - name: sds-demo
        env:
          - name: SITE_NAME
            value: "SDS Demo"
